language: node_js
node_js:
- node
- '7'
script:
- yarn run lint
- yarn run test
- gulp build

cache: yarn

deploy:
  provider: npm
  email: alex.servies@gmail.com
  api_key:
    secure: NxnfE2iVIMMuxIR+6u/29HBiz/bRQ16FX5xOZ5S3yvP7eFSD14xJnc476odZuOfrk+I5e86yceCIw5prZXaKBbWoCuVt1tr/ZFYwTbcab5yOoemlJDgOw8foVA6bM4/mOd6qpGKfnu3vizofRhHHM82d+MYSjFF2QD7GsQ+0k/4LfRWz8k9TpUC9Ov9h8+kpwZ0AnPPTVVHzp6kkN2wGqAPe2MUqrVran0yCgW9e7kBDD7yC0ycdrN3LD1huevEllH3Ww1lTqaMBgX5gfrXNEr0rP1Huyy6IV5JKDX61sWnrc8EbX9KpAWZB+IraMFlHNG7RSt33B9dLmVzr1vchvFVq63xYyA6KaYQ8rAGchZR+YPLoda5z6u+RPjeDn8oP4kTUFTUNjCEbaZfUGq97QEmHRB+z98psj/5P3Yhsr4XOK3zJaovy24moqLKx0fztkqJbEicHq0jEt0ju4EDuIEaX6kROUPQc8ZkoSCCETdwOp5XweeyM0N3mlbOUdAICIVgDB4eHx3KpvCh7+vmEAqQUvKM5KiNC2nLEm4kmGbdXjpAKl6o0LO3jA+NWoOqelPA/ObfsIp1953ZNxG5hZ/EpsqxaPVAUALEKGwFiYH8b3l6xEcJ2253h8E7XIe+jbRm3UsyfU1ZgI976UfwSgjm4FHIo4uyqaP3Vu1rsQE4=
  on:
    tags: true
    repo: AlexandreServies/hubot-even-better-help
    branch: master
  skip_cleanup: true
